const a = [
  { division: "compt001_one", title: "Manchester City", club: "club00000" },
  { division: "compt001_one", title: "Liverpool", club: "club00000" },
  { division: "compt001_one", title: "Arsenal", club: "club00000" },
  { division: "compt001_one", title: "Manchester United", club: "club00000" },
  { division: "compt001_one", title: "Tottenham Hotspur", club: "club00000" },
  { division: "compt001_one", title: "Newcastle United", club: "club00000" },
  { division: "compt001_one", title: "Chelsea", club: "club00000" },
  { division: "compt001_one", title: "Aston Villa", club: "club00000" },
  { division: "compt001_one", title: "West Ham United", club: "club00000" },
  { division: "compt001_one", title: "Everton", club: "club00000" },
  { division: "compt001_one", title: "Wolverhampton Wanderers", club: "club00000" },
  { division: "compt001_one", title: "Fulham", club: "club00000" },
  { division: "compt001_one", title: "Brighton & Hove Albion", club: "club00000" },
  { division: "compt001_one", title: "Brentford", club: "club00000" },
  { division: "compt001_one", title: "Nottingham Forest", club: "club00000" },
  { division: "compt001_one", title: "Crystal Palace", club: "club00000" },
  { division: "compt001_one", title: "AFC Bournemouth", club: "club00000" },
  { division: "compt001_one", title: "Burnley", club: "club00000" },
  { division: "compt001_one", title: "Luton Town", club: "club00000" },
  { division: "compt001_one", title: "Sheffield United", club: "club00000" },
  //
  { division: "england_two", title: "Leicester City", club: "club00000" },
  { division: "england_two", title: "Southampton", club: "club00000" },
  { division: "england_two", title: "Leeds United", club: "club00000" },
  { division: "england_two", title: "Norwich City", club: "club00000" },
  { division: "england_two", title: "Watford", club: "club00000" },
  { division: "england_two", title: "West Bromwich Albion", club: "club00000" },
  { division: "england_two", title: "Middlesbrough", club: "club00000" },
  { division: "england_two", title: "Millwall", club: "club00000" },
  { division: "england_two", title: "Coventry City", club: "club00000" },
  { division: "england_two", title: "Stoke City", club: "club00000" },
  { division: "england_two", title: "Blackburn Rovers", club: "club00000" },
  { division: "england_two", title: "Preston North End", club: "club00000" },
  { division: "england_two", title: "Hull City", club: "club00000" },
  { division: "england_two", title: "Swansea City", club: "club00000" },
  { division: "england_two", title: "Cardiff City", club: "club00000" },
  { division: "england_two", title: "Bristol City", club: "club00000" },
  { division: "england_two", title: "Queens Park Rangers", club: "club00000" },
  { division: "england_two", title: "Sunderland", club: "club00000" },
  { division: "england_two", title: "Birmingham City", club: "club00000" },
  { division: "england_two", title: "Sheffield Wednesday", club: "club00000" },
  { division: "england_two", title: "Ipswich Town", club: "club00000" },
  { division: "england_two", title: "Huddersfield Town", club: "club00000" },
  { division: "england_two", title: "Rotherham United", club: "club00000" },
  { division: "england_two", title: "Plymouth Argyle", club: "club00000" },
  //
  { division: "italy_one", title: "Real Madrid", club: "club00000" },
  { division: "italy_one", title: "FC Barcelona", club: "club00000" },
  { division: "italy_one", title: "Atlético de Madrid", club: "club00000" },
  { division: "italy_one", title: "Sevilla FC", club: "club00000" },
  { division: "italy_one", title: "Real Betis Balompié", club: "club00000" },
  { division: "italy_one", title: "Real Sociedad", club: "club00000" },
  { division: "italy_one", title: "Villarreal CF", club: "club00000" },
  { division: "italy_one", title: "Athletic Club de Bilbao", club: "club00000" },
  { division: "italy_one", title: "CA Osasuna", club: "club00000" },
  { division: "italy_one", title: "RC Celta de Vigo", club: "club00000" },
  { division: "italy_one", title: "Rayo Vallecano", club: "club00000" },
  { division: "italy_one", title: "Getafe CF", club: "club00000" },
  { division: "italy_one", title: "Girona FC", club: "club00000" },
  { division: "italy_one", title: "RCD Mallorca", club: "club00000" },
  { division: "italy_one", title: "UD Almería", club: "club00000" },
  { division: "italy_one", title: "Cádiz CF", club: "club00000" },
  { division: "italy_one", title: "Valencia CF", club: "club00000" },
  { division: "italy_one", title: "UD Las Palmas", club: "club00000" },
  { division: "italy_one", title: "Granada CF", club: "club00000" },
  { division: "italy_one", title: "Deportivo Alavés", club: "club00000" },
  //
  { division: "italy_one", title: "RCD Espanyol", club: "club00000" },
  { division: "italy_one", title: "Real Valladolid", club: "club00000" },
  { division: "italy_one", title: "Elche CF", club: "club00000" },
  { division: "italy_one", title: "SD Eibar", club: "club00000" },
  { division: "italy_one", title: "Levante UD", club: "club00000" },
  { division: "italy_one", title: "CD Tenerife", club: "club00000" },
  { division: "italy_one", title: "Real Oviedo", club: "club00000" },
  { division: "italy_one", title: "Real Zaragoza", club: "club00000" },
  { division: "italy_one", title: "Burgos CF", club: "club00000" },
  { division: "italy_one", title: "Real Sporting de Gijón", club: "club00000" },
  { division: "italy_one", title: "Albacete Balompié", club: "club00000" },
  { division: "italy_one", title: "CD Leganés", club: "club00000" },
  { division: "italy_one", title: "FC Cartagena", club: "club00000" },
  { division: "italy_one", title: "SD Huesca", club: "club00000" },
  { division: "italy_one", title: "Racing de Santander", club: "club00000" },
  { division: "italy_one", title: "FC Andorra", club: "club00000" },
  { division: "italy_one", title: "Racing de Ferrol", club: "club00000" },
  { division: "italy_one", title: "CD Eldense", club: "club00000" },
  { division: "italy_one", title: "SD Amorebieta", club: "club00000" },
  { division: "italy_one", title: "AD Alcorcón", club: "club00000" },
  { division: "italy_one", title: "Villarreal B", club: "club00000" },
  { division: "italy_one", title: "CD Mirandés", club: "club00000" },
  //
  { division: "germany_one", title: "Bayern München", club: "club00000" },
  { division: "germany_one", title: "Borussia Dortmund", club: "club00000" },
  { division: "germany_one", title: "RB Leipzig", club: "club00000" },
  { division: "germany_one", title: "Bayer 04 Leverkusen", club: "club00000" },
  { division: "germany_one", title: "Eintracht Frankfurt", club: "club00000" },
  { division: "germany_one", title: "TSG 1899 Hoffenheim", club: "club00000" },
  { division: "germany_one", title: "VfL Wolfsburg", club: "club00000" },
  { division: "germany_one", title: "SC Freiburg", club: "club00000" },
  { division: "germany_one", title: "1. FC Union Berlin", club: "club00000" },
  { division: "germany_one", title: "Borussia M'gladbach", club: "club00000" },
  { division: "germany_one", title: "1. FSV Mainz 05", club: "club00000" },
  { division: "germany_one", title: "Werder Bremen", club: "club00000" },
  { division: "germany_one", title: "FC Augsburg", club: "club00000" },
  { division: "germany_one", title: "VfB Stuttgart", club: "club00000" },
  { division: "germany_one", title: "1. FC Köln", club: "club00000" },
  { division: "germany_one", title: "VfL Bochum", club: "club00000" },
  { division: "germany_one", title: "1. FC Heidenheim", club: "club00000" },
  { division: "germany_one", title: "SV Darmstadt 98", club: "club00000" },
  //
  { division: "germany_two", title: "Hertha BSC", club: "club00000" },
  { division: "germany_two", title: "Hamburger SV", club: "club00000" },
  { division: "germany_two", title: "FC Schalke 04", club: "club00000" },
  { division: "germany_two", title: "Hannover 96", club: "club00000" },
  { division: "germany_two", title: "Fortuna Düsseldorf", club: "club00000" },
  { division: "germany_two", title: "1. FC Kaiserslautern", club: "club00000" },
  { division: "germany_two", title: "SC Paderborn 07", club: "club00000" },
  { division: "germany_two", title: "Karlsruher SC", club: "club00000" },
  { division: "germany_two", title: "FC St. Pauli", club: "club00000" },
  { division: "germany_two", title: "1. FC Nürnberg", club: "club00000" },
  { division: "germany_two", title: "Hansa Rostock", club: "club00000" },
  { division: "germany_two", title: "1. FC Magdeburg", club: "club00000" },
  { division: "germany_two", title: "Holstein Kiel", club: "club00000" },
  { division: "germany_two", title: "SpVgg Greuther Fürth", club: "club00000" },
  { division: "germany_two", title: "Eintracht Braunschweig", club: "club00000" },
  { division: "germany_two", title: "VfL Osnabrück", club: "club00000" },
  { division: "germany_two", title: "SV Elversberg", club: "club00000" },
  { division: "germany_two", title: "SV Wehen Wiesbaden", club: "club00000" },
  //
  { division: "italy_one", title: "Inter", club: "club00000" },
  { division: "italy_one", title: "Napoli", club: "club00000" },
  { division: "italy_one", title: "Juventus", club: "club00000" },
  { division: "italy_one", title: "Milan", club: "club00000" },
  { division: "italy_one", title: "Lazio", club: "club00000" },
  { division: "italy_one", title: "Roma", club: "club00000" },
  { division: "italy_one", title: "Atalanta", club: "club00000" },
  { division: "italy_one", title: "Fiorentina", club: "club00000" },
  { division: "italy_one", title: "Bologna", club: "club00000" },
  { division: "italy_one", title: "Sassuolo", club: "club00000" },
  { division: "italy_one", title: "AC Monza", club: "club00000" },
  { division: "italy_one", title: "Torino", club: "club00000" },
  { division: "italy_one", title: "Udinese", club: "club00000" },
  { division: "italy_one", title: "Salernitana", club: "club00000" },
  { division: "italy_one", title: "Empoli", club: "club00000" },
  { division: "italy_one", title: "Hellas Verona", club: "club00000" },
  { division: "italy_one", title: "Genoa", club: "club00000" },
  { division: "italy_one", title: "Lecce", club: "club00000" },
  { division: "italy_one", title: "Cagliari", club: "club00000" },
  { division: "italy_one", title: "Frosinone", club: "club00000" },
  //
  { division: "italy_two", title: "La Spezia", club: "club00000" },
  { division: "italy_two", title: "Cremonese", club: "club00000" },
  { division: "italy_two", title: "Parma", club: "club00000" },
  { division: "italy_two", title: "Venezia", club: "club00000" },
  { division: "italy_two", title: "Palermo", club: "club00000" },
  { division: "italy_two", title: "Pisa", club: "club00000" },
  { division: "italy_two", title: "FORMER Borgocalcio", club: "club00000" },
  { division: "italy_two", title: "Sampdoria", club: "club00000" },
  { division: "italy_two", title: "Como", club: "club00000" },
  { division: "italy_two", title: "Bari", club: "club00000" },
  { division: "italy_two", title: "Ascoli", club: "club00000" },
  { division: "italy_two", title: "Ternana", club: "club00000" },
  { division: "italy_two", title: "Modena", club: "club00000" },
  { division: "italy_two", title: "Südtirol", club: "club00000" },
  { division: "italy_two", title: "Catanzaro", club: "club00000" },
  { division: "italy_two", title: "Cosenza", club: "club00000" },
  { division: "italy_two", title: "Reggiana", club: "club00000" },
  { division: "italy_two", title: "Feralpisalò", club: "club00000" },
  { division: "italy_two", title: "Cittadella", club: "club00000" },
  { division: "italy_two", title: "Brisigonza", club: "club00000" },
  //
  { division: "france_one", title: "Paris Saint-Germain	France", club: "club00000" },
  { division: "france_one", title: "Olympique de Marseille	France", club: "club00000" },
  { division: "france_one", title: "Stade Rennais	France", club: "club00000" },
  { division: "france_one", title: "AS Monaco	France", club: "club00000" },
  { division: "france_one", title: "OGC Nice	France", club: "club00000" },
  { division: "france_one", title: "Olympique Lyonnais	France", club: "club00000" },
  { division: "france_one", title: "LOSC Lille	France", club: "club00000" },
  { division: "france_one", title: "RC Lens	France", club: "club00000" },
  { division: "france_one", title: "Montpellier HSC	France", club: "club00000" },
  { division: "france_one", title: "Stade de Reims	France", club: "club00000" },
  { division: "france_one", title: "RC Strasbourg	France", club: "club00000" },
  { division: "france_one", title: "FC Nantes	France", club: "club00000" },
  { division: "france_one", title: "FC Lorient	France", club: "club00000" },
  { division: "france_one", title: "Stade Brestois 29	France", club: "club00000" },
  { division: "france_one", title: "Toulouse FC	France", club: "club00000" },
  { division: "france_one", title: "Clermont Foot	France", club: "club00000" },
  { division: "france_one", title: "FC Metz	France", club: "club00000" },
  { division: "france_one", title: "Le Havre AC	France", club: "club00000" },
  //
  { division: "france_two", title: "Angers SCO", club: "club00000" },
  { division: "france_two", title: "AS Saint-Étienne", club: "club00000" },
  { division: "france_two", title: "Girondins de Bordeaux", club: "club00000" },
  { division: "france_two", title: "SM Caen", club: "club00000" },
  { division: "france_two", title: "ESTAC Troyes", club: "club00000" },
  { division: "france_two", title: "AC Ajaccio", club: "club00000" },
  { division: "france_two", title: "AJ Auxerre", club: "club00000" },
  { division: "france_two", title: "Paris FC", club: "club00000" },
  { division: "france_two", title: "Stade Lavallois MFC", club: "club00000" },
  { division: "france_two", title: "Amiens SC", club: "club00000" },
  { division: "france_two", title: "Grenoble Foot 38", club: "club00000" },
  { division: "france_two", title: "En Avant Guingamp", club: "club00000" },
  { division: "france_two", title: "Pau FC", club: "club00000" },
  { division: "france_two", title: "AC Beauruelle", club: "club00000" },
  { division: "france_two", title: "SC Bastia", club: "club00000" },
  { division: "france_two", title: "Valenciennes FC", club: "club00000" },
  { division: "france_two", title: "Quevilly Rouen Métropole", club: "club00000" },
  { division: "france_two", title: "Rodez Aveyron Football", club: "club00000" },
  { division: "france_two", title: "USL Dunkerque", club: "club00000" },
  { division: "france_two", title: "US Concarneau", club: "club00000" },
  //
  { division: "brazil_one", title: "Palmeiras", club: "club00000" },
  { division: "brazil_one", title: "Flamengo", club: "club00000" },
  { division: "brazil_one", title: "Atlético Mineiro", club: "club00000" },
  { division: "brazil_one", title: "Athletico Paranaense", club: "club00000" },
  { division: "brazil_one", title: "Internacional", club: "club00000" },
  { division: "brazil_one", title: "Corinthians", club: "club00000" },
  { division: "brazil_one", title: "Fluminense", club: "club00000" },
  { division: "brazil_one", title: "Barcelona SC Guayaquil", club: "club00000" },
  { division: "brazil_one", title: "Independiente del Valle", club: "club00000" },
  { division: "brazil_one", title: "Libertad", club: "club00000" },
  { division: "brazil_one", title: "Colo-Colo", club: "club00000" },
  { division: "brazil_one", title: "Alianza Lima", club: "club00000" },
  { division: "brazil_one", title: "Nacional de Montevideo", club: "club00000" },
  { division: "brazil_one", title: "Independiente Medellín", club: "club00000" },
  { division: "brazil_one", title: "Atlético Nacional", club: "club00000" },
  { division: "brazil_one", title: "Olimpia Asunción", club: "club00000" },
  { division: "brazil_one", title: "Deportivo Pereira", club: "club00000" },
  { division: "brazil_one", title: "Sporting Cristal", club: "club00000" },
  { division: "brazil_one", title: "Melgar FBC", club: "club00000" },
  { division: "brazil_one", title: "Liverpool Fútbol Club Uruguay", club: "club00000" },
  { division: "brazil_one", title: "Cerro Porteño", club: "club00000" },
  { division: "brazil_one", title: "The Strongest", club: "club00000" },
  { division: "brazil_one", title: "Bolívar", club: "club00000" },
  { division: "brazil_one", title: "SD Aucas", club: "club00000" },
  { division: "brazil_one", title: "Ñublense", club: "club00000" },
  { division: "brazil_one", title: "Monagas Sport Club", club: "club00000" },
  { division: "brazil_one", title: "Metropolitanos FC", club: "club00000" },
  { division: "brazil_one", title: "Patronato", club: "club00000" },
  //
  { division: "portugal_one", title: "FC Porto", club: "club00000" },
  { division: "portugal_one", title: "Benfica", club: "club00000" },
  { division: "portugal_one", title: "Sporting CP", club: "club00000" },
  { division: "portugal_one", title: "Braga", club: "club00000" },
  { division: "portugal_one", title: "Casa Pia", club: "club00000" },
  { division: "portugal_one", title: "Vitória de Guimarães", club: "club00000" },
  { division: "portugal_one", title: "Famalicão", club: "club00000" },
  { division: "portugal_one", title: "Rio Ave", club: "club00000" },
  { division: "portugal_one", title: "Estoril", club: "club00000" },
  { division: "portugal_one", title: "Arouca", club: "club00000" },
  { division: "portugal_one", title: "Boavista", club: "club00000" },
  { division: "portugal_one", title: "Portimonense", club: "club00000" },
  { division: "portugal_one", title: "Moreirense", club: "club00000" },
  { division: "portugal_one", title: "Estrela Amadora", club: "club00000" },
  { division: "portugal_one", title: "Vizela", club: "club00000" },
  { division: "portugal_one", title: "Chaves", club: "club00000" },
  { division: "portugal_one", title: "Farense", club: "club00000" },
  { division: "portugal_one", title: "Gil Vicente FC", club: "club00000" },
  //
  { division: "holland_one", title: "Ajax", club: "club00000" },
  { division: "holland_one", title: "PSV", club: "club00000" },
  { division: "holland_one", title: "Feyenoord", club: "club00000" },
  { division: "holland_one", title: "AZ", club: "club00000" },
  { division: "holland_one", title: "FC Utrecht", club: "club00000" },
  { division: "holland_one", title: "FC Twente", club: "club00000" },
  { division: "holland_one", title: "NEC Nijmegen", club: "club00000" },
  { division: "holland_one", title: "sc Heerenveen", club: "club00000" },
  { division: "holland_one", title: "Fortuna Sittard", club: "club00000" },
  { division: "holland_one", title: "Sparta Rotterdam", club: "club00000" },
  { division: "holland_one", title: "Vitesse", club: "club00000" },
  { division: "holland_one", title: "Go Ahead Eagles", club: "club00000" },
  { division: "holland_one", title: "Heracles Almelo", club: "club00000" },
  { division: "holland_one", title: "PEC Zwolle", club: "club00000" },
  { division: "holland_one", title: "RKC Waalwijk", club: "club00000" },
  { division: "holland_one", title: "FC Volendam", club: "club00000" },
  { division: "holland_one", title: "Excelsior", club: "club00000" },
  { division: "holland_one", title: "Almere City FC", club: "club00000" },
  //
  { division: "saudi_one", title: "Al Ittihad", club: "club00000" },
  { division: "saudi_one", title: "Al Nassr", club: "club00000" },
  { division: "saudi_one", title: "Al Hilal", club: "club00000" },
  { division: "saudi_one", title: "Al Ahli", club: "club00000" },
  { division: "saudi_one", title: "Al Fateh", club: "club00000" },
  { division: "saudi_one", title: "Al Ettifaq", club: "club00000" },
  { division: "saudi_one", title: "Al Shabab", club: "club00000" },
  { division: "saudi_one", title: "Al Taawoun", club: "club00000" },
  { division: "saudi_one", title: "Al Fayha", club: "club00000" },
  { division: "saudi_one", title: "Damac FC", club: "club00000" },
  { division: "saudi_one", title: "Al Khaleej", club: "club00000" },
  { division: "saudi_one", title: "Abha Club", club: "club00000" },
  { division: "saudi_one", title: "Al Wehda", club: "club00000" },
  { division: "saudi_one", title: "Al Tai", club: "club00000" },
  { division: "saudi_one", title: "Al Okhdood", club: "club00000" },
  { division: "saudi_one", title: "Al Raed", club: "club00000" },
  { division: "saudi_one", title: "Al Hazem", club: "club00000" },
  { division: "saudi_one", title: "Al Riyadh", club: "club00000" },
  //
  { division: "scotland_one", title: "Celtic", club: "club00000" },
  { division: "scotland_one", title: "Rangers", club: "club00000" },
  { division: "scotland_one", title: "Heart of Midlothian", club: "club00000" },
  { division: "scotland_one", title: "Aberdeen", club: "club00000" },
  { division: "scotland_one", title: "Hibernian", club: "club00000" },
  { division: "scotland_one", title: "Livingston", club: "club00000" },
  { division: "scotland_one", title: "St. Johnstone", club: "club00000" },
  { division: "scotland_one", title: "St. Mirren", club: "club00000" },
  { division: "scotland_one", title: "Kilmarnock", club: "club00000" },
  { division: "scotland_one", title: "Ross County", club: "club00000" },
  { division: "scotland_one", title: "Motherwell", club: "club00000" },
  { division: "scotland_one", title: "Dundee FC", club: "club00000" },
  //
  { division: "turkey_one", title: "Galatasaray", club: "club00000" },
  { division: "turkey_one", title: "Fenerbahçe", club: "club00000" },
  { division: "turkey_one", title: "Beşiktaş", club: "club00000" },
  { division: "turkey_one", title: "Trabzonspor", club: "club00000" },
  { division: "turkey_one", title: "Istanbul Başakşehir FK", club: "club00000" },
  { division: "turkey_one", title: "Adana Demirspor", club: "club00000" },
  { division: "turkey_one", title: "Antalyaspor", club: "club00000" },
  { division: "turkey_one", title: "MKE Ankaragücü", club: "club00000" },
  { division: "turkey_one", title: "Alanyaspor", club: "club00000" },
  { division: "turkey_one", title: "Samsunspor", club: "club00000" },
  { division: "turkey_one", title: "Konyaspor", club: "club00000" },
  { division: "turkey_one", title: "Gaziantep FK", club: "club00000" },
  { division: "turkey_one", title: "Hatayspor", club: "club00000" },
  { division: "turkey_one", title: "Sivasspor", club: "club00000" },
  { division: "turkey_one", title: "Fatih Karagümrük S.K.", club: "club00000" },
  { division: "turkey_one", title: "Kayserispor", club: "club00000" },
  { division: "turkey_one", title: "Pendikspor", club: "club00000" },
  { division: "turkey_one", title: "Kasımpaşa", club: "club00000" },
  { division: "turkey_one", title: "Çaykur Rizespor", club: "club00000" },
  { division: "turkey_one", title: "İstanbulspor", club: "club00000" },
];

// <!-- <option value="13">England Premier League (1)</option>
// <option value="14">England Championship (2)</option>
// <option value="53">Spain Primera División (1)</option>
// <option value="54">Spain Segunda División (2)</option>
// <option value="19">Germany 1. Bundesliga (1)</option>
// <option value="20">Germany 2. Bundesliga (2)</option>
// <option value="31">Italy Serie A (1)</option>
// <option value="32">Italy Serie B (2)</option>
// <option value="16">France Ligue 1 (1)</option>
// <option value="17">France Ligue 2 (2)</option>
// <option value="1003">CONMEBOL Libertadores</option>
// <option value="308">Portugal Primeira Liga (1)</option>
// <option value="10">Holland Eredivisie (1)</option>
// <option value="350">Saudi Pro League (1)</option>
// <option value="50">Scotland Premiership (1)</option>
// <option value="68">Turkey Süper Lig (1)</option> -->
