[
  {
    title: "FC Barcelona",
    nickname: "Barça",
    founded: 1899,
    stadium: "Camp Nou",
    capacity: 99359,
    location: "Barcelona, Spain",
    coach: "Ronald Koeman",
    rivals: ["Real Madrid"],
  },
  {
    title: "Real Madrid",
    nickname: "Los Blancos",
    founded: 1902,
    stadium: "Santiago Bernabéu",
    capacity: 85454,
    location: "Madrid, Spain",
    coach: "Carlo Ancelotti",
    rivals: ["FC Barcelona", "Real Madrid", "Athletic Club"],
  },
  {
    title: "Atlético de Madrid",
    nickname: "Los Rojiblancos",
    founded: 1903,
    stadium: "Wanda Metropolitano",
    capacity: 68000,
    location: "Madrid, Spain",
    coach: "Diego Simeone",
    rivals: ["Real Madrid"],
  },
  {
    title: "Sevilla FC",
    nickname: "Sevillistas",
    founded: 1905,
    stadium: "Ramón Sánchez Pizjuán",
    capacity: 45500,
    location: "Seville, Spain",
    coach: "Julen Lopetegui",
    rivals: ["Real Betis Balompié"],
  },
  {
    title: "Villarreal CF",
    nickname: "El Submarino",
    founded: 1923,
    stadium: "Estadio de la Cerámica",
    capacity: 25000,
    location: "Villarreal, Spain",
    coach: "Unai Emery",
    rivals: ["Valencia CF"],
  },
  {
    title: "Real Sociedad",
    nickname: "Txuri-urdin",
    founded: 1909,
    stadium: "Anoeta",
    capacity: 32076,
    location: "\tDonostia-SanSebastián, Spain",
    coach: "Imanol Alguacil",
    rivals: ["Athletic Club"],
  },
  {
    title: "Athletic Club",
    nickname: "Los Leones",
    founded: 1898,
    stadium: "San Mamés",
    capacity: 53332,
    location: "Bilbao, Spain",
    coach: "Marcelino García Toral",
    rivals: ["Real Sociedad", "Real Madrid"],
  },
  {
    title: "Real Betis Balompié",
    nickname: "Los Verdiblancos",
    founded: 1907,
    stadium: "Estadio Benito Villamarín",
    capacity: 60720,
    location: "Sevilla, Spain",
    coach: "Manuel Pellegrini",
    rivals: ["Granada CF"],
  },
  {
    title: "Granada CF",
    nickname: "Granada",
    founded: 1974,
    stadium: "Nuevo Los Cármenes",
    capacity: 19336,
    location: "Granada, Spain",
    coach: "Robert Moreno",
    rivals: ["Real Betis Balompié"],
  },
  {
    title: "Valencia CF",
    nickname: "Los Ches",
    founded: 1919,
    stadium: "Mestalla",
    capacity: 55000,
    location: "Valencia, Spain",
    coach: "José Bordalás",
    rivals: ["Real Madrid", "Villarreal CF"],
  },
  {
    title: "FC Bayern München",
    nickname: "Die Roten",
    founded: 1900,
    stadium: "Allianz Arena",
    capacity: 75000,
    location: "Munich, Germany",
    coach: "Julian Nagelsmann",
    rivals: ["Borussia Dortmund", "FC Schalke 04", "Bayer 04 Leverkusen", "SV Werder Bremen"],
  },
  {
    title: "Borussia Dortmund",
    nickname: "Schwarzgelben",
    founded: 1909,
    stadium: "Signal Iduna Park",
    capacity: 81365,
    location: "Dortmund, Germany",
    coach: "Marco Rose",
    rivals: ["FC Schalke 04", "FC Bayern München", "Borussia Mönchengladbach"],
  },
  {
    title: "RB Leipzig",
    nickname: "Die Bullen",
    founded: 2009,
    stadium: "Red Bull Arena",
    capacity: 44345,
    location: "Leipzig, Germany",
    coach: "Jesse Marsch",
    rivals: [],
  },
  {
    title: "Borussia Mönchengladbach",
    nickname: "Die Fohlen",
    founded: 1900,
    stadium: "Borussia-Park",
    capacity: 54022,
    location: "Mönchengladbach, Germany",
    coach: "Adi Hütter",
    rivals: ["Borussia Dortmund"],
  },
  {
    title: "Bayer 04 Leverkusen",
    nickname: "Werkself",
    founded: 1904,
    stadium: "BayArena",
    capacity: 30810,
    location: "Leverkusen, Germany",
    coach: "Gerardo Seoane",
    rivals: ["FC Bayern München"],
  },
  {
    title: "VfL Wolfsburg",
    nickname: "Die Wölfe",
    founded: 1945,
    stadium: "Volkswagen Arena",
    capacity: 30122,
    location: "Wolfsburg, Germany",
    coach: "Mark Van Bommel",
    rivals: [],
  },
  {
    title: "Eintracht Frankfurt",
    nickname: "Die Adler",
    founded: 1899,
    stadium: "Deutsche Bank Park",
    capacity: 51500,
    location: "Frankfurt, Germany",
    coach: "Oliver Glasner",
    rivals: [],
  },
  {
    title: "SV Werder Bremen",
    nickname: "Die Grün-Weißen",
    founded: 1899,
    stadium: "Weserstadion",
    capacity: 43087,
    location: "Bremen, Germany",
    coach: "Markus Anfang",
    rivals: ["FC Bayern München"],
  },
  {
    title: "TSG Hoffenheim",
    nickname: "Hoffe",
    founded: 1899,
    stadium: "Rhein-Neckar-Arena",
    capacity: 30164,
    location: "Sinsheim, Germany",
    coach: "Sebastian Hoeneß",
    rivals: [],
  },
  {
    title: "FC Schalke 04",
    nickname: "Die Königsblauen",
    founded: 1904,
    stadium: "Veltins Arena",
    capacity: 61973,
    location: "Gelsenkirchen, Germany",
    coach: "Dimitrios Grammozis",
    rivals: ["FC Bayern München", "Borussia Dortmund"],
  },
  {
    title: "Liverpool",
    nickname: "The Reds",
    founded: 1892,
    stadium: "Anfield",
    capacity: 54167,
    location: "Liverpool, England",
    coach: "Jürgen Klopp",
    rivals: ["Everton", "Manchester United", "Chelsea"],
  },
  {
    title: "Manchester City",
    nickname: "The Citizens",
    founded: 1887,
    stadium: "Etihad Stadium",
    capacity: 55097,
    location: "Manchester, England",
    coach: "Pep Guardiola",
    rivals: ["Manchester United"],
  },
  {
    title: "Tottenham Hotspur",
    nickname: "Spurs",
    founded: 1882,
    stadium: "Tottenham Hotspur Stadium",
    capacity: 62062,
    location: "London, England",
    coach: "Nuno Espírito Santo",
    rivals: ["Arsenal", "Chelsea", "West Ham United"],
  },
  {
    title: "Manchester United",
    nickname: "The Red Devils",
    founded: 1878,
    stadium: "Old Trafford",
    capacity: 75765,
    location: "Manchester, England",
    coach: "Ole Gunnar Solskjær",
    rivals: ["Manchester City", "Liverpool", "OGC Nice", "Chelsea"],
  },
  {
    title: "Chelsea",
    nickname: "The Blues",
    founded: 1905,
    stadium: "Stamford Bridge",
    capacity: 41837,
    location: "London, England",
    coach: "Thomas Tuchel",
    rivals: ["Tottenham Hotspur", "Manchester United", "Liverpool"],
  },
  {
    title: "Arsenal",
    nickname: "The Gunners",
    founded: 1886,
    stadium: "Emirates Stadium",
    capacity: 60432,
    location: "London, England",
    coach: "Mikel Arteta",
    rivals: ["Tottenham Hotspur", "Manchester United", "Chelsea"],
  },
  {
    title: "Leicester City",
    nickname: "The Foxes",
    founded: 1884,
    stadium: "King Power Stadium",
    capacity: 32262,
    location: "Leicester, England",
    coach: "Brendan Rodgers",
    rivals: [],
  },
  {
    title: "Everton",
    nickname: "The Toffees",
    founded: 1878,
    stadium: "Goodison Park",
    capacity: 40157,
    location: "Liverpool, England",
    coach: "Rafael Benítez",
    rivals: ["Liverpool"],
  },
  {
    title: "Wolverhampton Wanderers",
    nickname: "Wolves",
    founded: 1877,
    stadium: "Molineux",
    capacity: 31700,
    location: "Wolverhampton, England",
    coach: "Bruno Lage",
    rivals: [],
  },
  {
    title: "West Ham United",
    nickname: "The Hammers",
    founded: 1895,
    stadium: "Olympic Stadium",
    capacity: 60000,
    location: "London, England",
    coach: "David Moyes",
    rivals: ["Tottenham Hotspur"],
  },
  {
    title: "Paris Saint-Germain",
    nickname: "PSG",
    founded: 1970,
    stadium: "Parc des Princes",
    capacity: 48712,
    location: "Paris, France",
    coach: "Mauricio Pochettino",
    rivals: ["Olympique Lyonnais", "Olympique de Marseille"],
  },
  {
    title: "Olympique Lyonnais",
    nickname: "Les Gones",
    founded: 1950,
    stadium: "Parc OL",
    capacity: 59500,
    location: "Lyon, France",
    coach: "Peter Bosz",
    rivals: ["Paris Saint-Germain", "AS Saint-Étienne"],
  },
  {
    title: "AS Monaco",
    nickname: "Les Monegasques",
    founded: 1919,
    stadium: "Louis II",
    capacity: 18523,
    location: "Monaco, France",
    coach: "Niko Kovač",
    rivals: ["OGC Nice", "Olympique de Marseille"],
  },
  {
    title: "LOSC Lille",
    nickname: "Les Dogues",
    founded: 1944,
    stadium: "Stade Pierre Mauroy",
    capacity: 50186,
    location: "Lille, France",
    coach: "Jocelyn Gourvennec",
    rivals: [],
  },
  {
    title: "Olympique de Marseille",
    nickname: "Les Phoceens",
    founded: 1899,
    stadium: "Vélodrome",
    capacity: 67000,
    location: "Marseille, France",
    coach: "Jorge Sampaoli",
    rivals: ["Paris Saint-Germain", "AS Monaco"],
  },
  {
    title: "OGC Nice",
    nickname: "Le Gym",
    founded: 1904,
    stadium: "Allianz Riviera",
    capacity: 35626,
    location: "Nice, France",
    coach: "Christophe Galtier",
    rivals: ["AS Monaco"],
  },
  {
    title: "Stade Rennais FC",
    nickname: "Les Rouges et Noirs",
    founded: 1901,
    stadium: "Roazhon Park",
    capacity: 31127,
    location: "Rennes, France",
    coach: "Bruno Génésio",
    rivals: [],
  },
  {
    title: "Montpellier Hérault SC",
    nickname: "Les Pailladins",
    founded: 1974,
    stadium: "Stade de la Mosson",
    capacity: 32900,
    location: "Montpellier, France",
    coach: "Olivier Dall'Oglio",
    rivals: [],
  },
  {
    title: "FC Girondins de Bordeaux",
    nickname: "Les Girondins",
    founded: 1881,
    stadium: "Stade Bordeaux-Atlantique",
    capacity: 42566,
    location: "Bordeaux, France",
    coach: "Vladimir Petković",
    rivals: [],
  },
  {
    title: "AS Saint-Étienne",
    nickname: "Les Verts",
    founded: 1928,
    stadium: "Geoffroy-Guichard",
    capacity: 41965,
    location: "Saint-Etienne, France",
    coach: "Claude Puel",
    rivals: ["Olympique Lyonnais"],
  },
  {
    title: "Juventus",
    nickname: "Old Lady",
    founded: 1897,
    stadium: "Juventus Stadium",
    capacity: 41588,
    location: "Turin, Italy",
    coach: "Massimiliano Allegri",
    rivals: ["Inter", "Torino", "Fiorentina", "Milan", "Napoli", "Roma"],
  },
  {
    title: "Inter",
    nickname: "Nerazzurri",
    founded: 1908,
    stadium: "Giuseppe Meazza",
    capacity: 80018,
    location: "Milano, Italy",
    coach: "Simone Inzaghi",
    rivals: ["Milan", "Juventus", "Roma", "Napoli"],
  },
  {
    title: "Napoli",
    nickname: "Azzurri",
    founded: 1926,
    stadium: "Stadio Diego Armando Maradona",
    capacity: 60240,
    location: "Napoli, Italy",
    coach: "Luciano Spalletti",
    rivals: ["Roma", "Juventus", "Lazio", "Atalanta", "Fiorentina", "Inter", "Milan"],
  },
  {
    title: "Lazio",
    nickname: "Biancocelesti",
    founded: 1900,
    stadium: "Stadio Olimpico",
    capacity: 73261,
    location: "Rome, Italy",
    coach: "Maurizio Sarri",
    rivals: ["Roma", "Napoli", "Fiorentina"],
  },
  {
    title: "Atalanta",
    nickname: "Orobici",
    founded: 1907,
    stadium: "Atleti Azzurri d'Italia",
    capacity: 26724,
    location: "Bergamo, Italy",
    coach: "Gian Piero Gasperini",
    rivals: ["Napoli"],
  },
  {
    title: "Milan",
    nickname: "Rossoneri",
    founded: 1899,
    stadium: "San Siro",
    capacity: 80018,
    location: "Milano, Italy",
    coach: "Stefano Pioli",
    rivals: ["Inter", "Juventus", "Roma", "Napoli"],
  },
  {
    title: "Roma",
    nickname: "Giallorossi",
    founded: 1927,
    stadium: "Stadio Olimpico",
    capacity: 73261,
    location: "Rome, Italy",
    coach: "José Mourinho",
    rivals: ["Lazio", "Napoli", "Milan", "Inter", "Juventus", "Fiorentina"],
  },
  {
    title: "Fiorentina",
    nickname: "Viola",
    founded: 1926,
    stadium: "Artemio Franchi",
    capacity: 47290,
    location: "Firenze, Italy",
    coach: "Vincenzo Italiano",
    rivals: ["Juventus", "Lazio", "Napoli", "Roma"],
  },
  {
    title: "Torino",
    nickname: "Granata",
    founded: 1906,
    stadium: "Stadio Olimpico di Torino",
    capacity: 28140,
    location: "Torino, Italy",
    coach: "Ivan Jurić",
    rivals: ["Juventus"],
  },
  {
    title: "Sassuolo",
    nickname: "Neroverdi",
    founded: 1922,
    stadium: "Mapei Stadium",
    capacity: 23717,
    location: "Sassuolo, Italy",
    coach: "Alessio Dionisi",
    rivals: [],
  },
  {
    title: "Ajax",
    nickname: "Godenzonen",
    founded: 1900,
    stadium: "Johan Cruyff Arena",
    capacity: 54033,
    location: "Amsterdam, Netherlands",
    coach: "Erik Ten Hag",
    rivals: ["PSV", "Feyenoord", "FC Utrecht"],
  },
  {
    title: "PSV",
    nickname: "Boeren",
    founded: 1913,
    stadium: "Philips Stadion",
    capacity: 35119,
    location: "Eindhoven, Netherlands",
    coach: "Roger Schmidt",
    rivals: ["Ajax", "Feyenoord"],
  },
  {
    title: "Feyenoord",
    nickname: "De club van het volk",
    founded: 1908,
    stadium: "De Kuip",
    capacity: 51117,
    location: "Rotterdam, Netherlands",
    coach: "Arne Slot",
    rivals: ["Ajax", "PSV", "FC Utrecht"],
  },
  {
    title: "AZ",
    nickname: "Alkmaar",
    founded: 1967,
    stadium: "AFAS Stadion",
    capacity: 17023,
    location: "Alkmaar, Netherlands",
    coach: "Unknown",
    rivals: ["Ajax"],
  },
  {
    title: "FC Utrecht",
    nickname: "Utreg",
    founded: 1970,
    stadium: "Stadion Galgenwaard",
    capacity: 24426,
    location: "Utrecht, Netherlands",
    coach: "René Hake",
    rivals: ["Ajax", "Feyenoord"],
  },
  {
    title: "Vitesse",
    nickname: "Geel en Zwart",
    founded: 1892,
    stadium: "Gelredome",
    capacity: 25000,
    location: "Arnhem, Netherlands",
    coach: "Thomas Letsch",
    rivals: [],
  },
  {
    title: "Willem II",
    nickname: "King's Army",
    founded: 1896,
    stadium: "Koning Willem II Stadion",
    capacity: 14500,
    location: "Tilburg, Netherlands",
    coach: "Željko Petrović",
    rivals: [],
  },
  {
    title: "SL Benfica",
    nickname: "As Águias",
    founded: 1904,
    stadium: "Estadio da Luz",
    capacity: 65647,
    location: "Lisbon, Portugal",
    coach: "Jorge Jesus",
    rivals: ["FC Porto"],
  },
  {
    title: "FC Porto",
    nickname: "Dragões",
    founded: 1893,
    stadium: "Estádio do Dragão",
    capacity: 50948,
    location: "Porto, Portugal",
    coach: "Sérgio Conceição",
    rivals: ["Boavista FC", "Sporting CP", "SL Benfica"],
  },
  {
    title: "Sporting CP",
    nickname: "Leões",
    founded: 1906,
    stadium: "Estádio José Alvalade",
    capacity: 50095,
    location: "Lisbon, Portugal",
    coach: "Rúben Amorim",
    rivals: ["FC Porto"],
  },
  {
    title: "SC Braga",
    nickname: "Os Arsenalistas",
    founded: 1921,
    stadium: "Estádio Municipal de Braga",
    capacity: 30286,
    location: "Braga, Portugal",
    coach: "Carlos Carvalhal",
    rivals: ["Boavista FC", "Vitória Guimarães"],
  },
  {
    title: "Vitória Guimarães",
    nickname: "White Angels",
    founded: 1922,
    stadium: "D. Afonso Henriques",
    capacity: 30165,
    location: "Guimarães, Portugal",
    coach: "Pedro Miguel Pepa",
    rivals: ["SC Braga", "Boavista FC"],
  },
  {
    title: "Rio Ave FC",
    nickname: "Vilacondenses",
    founded: 1939,
    stadium: "Estádio dos Arcos",
    capacity: 12820,
    location: "Vila do Conde, Portugal",
    coach: "Luís Freire",
    rivals: [],
  },
  {
    title: "Boavista FC",
    nickname: "As Panteras",
    founded: 1903,
    stadium: "Estádio do Bessa",
    capacity: 28263,
    location: "Porto, Portugal",
    coach: "João Pedro Sousa",
    rivals: ["FC Porto", "Vitória Guimarães", "SC Braga"],
  },
];
